services:
    bb3mobi.lastpostavatar.listener:
        class: bb3mobi\lastpostavatar\event\listener
        arguments:
            - @user
            - @path_helper
            - @dbal.conn
        tags:
            - { name: event.listener }
